name: Prueba Proxy
version: "1.4"
panel_icon: "mdi:alert-circle-outline"
panel_title: Prueba Proxy
slug: prueba-proxy
description: Proxy addon for Prueba
url: "https://github.com/blakeblackshear/frigate"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:81]/"
watchdog: "http://[HOST]:[PORT:81]/"
ingress: true
ingress_port: 81
ingress_entry: /
panel_admin: false
ports:
  81/tcp: 81
ports_description:
  81/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "http://prueba.local:81"
  proxy_pass_host: true
schema:
  server: "match(^https?://.+:\\d+$)"
  proxy_pass_host: bool
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
